drm/amdkcl: fix missing do_mccs argument in dm_dp_destroy_mst_connector
it's caused by ed2c0d91ea4e140531
"drm/amd/display: Avoid to do MCCS transaction if unnecessary"


Commit ed2c0d91ea4e ("drm/amd/display: Avoid to do MCCS transaction if
unnecessary") added a third parameter 'bool do_mccs' to
amdgpu_dm_update_freesync_caps() and updated most call sites, but
missed the one in dm_dp_destroy_mst_connector().

This causes a build failure on DKMS targets:

  amdgpu_dm_mst_types.c:987: error: too few arguments to function
  'amdgpu_dm_update_freesync_caps'

Pass true to maintain the original behaviour of performing the MCCS
transaction during MST connector destruction.

Signed-off-by: Yang Su <Yang.Su2@amd.com>
Reviewed-by: Chengjun Yao <Chengjun.Yao@amd.com>