drm/amdgpu: Fix parameter compatibility issue in amdgpu_vkms_early_init
GCC raises a parameter compatibility error log for the
amdgpu_vkms_early_init function because it previously accepted
a generic `void *handle` parameter. This change updates the
function signature to accept a specific `struct amdgpu_ip_block *`
parameter instead.

error log:
/tmp/amd.fwXY79Rm/amd/amdgpu/amdgpu_vkms.c:805:16: error:
initialization of ‘int (*)(struct amdgpu_ip_block *)’ from
incompatible pointer type ‘int (*)(void *)’ [-Werror=incompatible-pointer-types]
.early_init = amdgpu_vkms_early_init,

Reviewed-by: Alex Deucher <alexander.deucher@amd.com>
Acked-by:  Yifan Zhang <yifan1.zhang@amd.com>
Signed-off-by: Perry Yuan <perry.yuan@amd.com>